[project]
name = "nvim"
version = "0.1.0"
description = "Python packages for Neovim"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "jupytext>=1.17.2",
    "nbformat>=5.10.4",
]
